import express from "express";
import fetch from "node-fetch";
import "dotenv/config";

/**
 * Amazon B2B6 remaining-five LIVE resume v1.0.0
 * 2026-08-29
 *
 * The first SKU was already submitted by the original B2B6 LIVE batch and is now
 * fully propagated at 57,000. This route NEVER writes that SKU. It is a mandatory
 * guard proving the prior submission completed before any remaining write occurs.
 *
 * Exact remaining scope: five SKUs only. Each must still have no explicit B2B
 * attribute and its original actual B2B offer before this route may write it.
 * This makes the route non-rerunnable after any successful submission.
 *
 * Flow:
 * - Fresh guard first SKU + Fresh preflight all remaining five
 * - VALIDATION_PREVIEW all remaining five
 * - Fresh guard/preflight all again
 * - For each remaining SKU: Fresh preflight -> one LIVE PATCH, no retry
 * - Verify explicit B2B attribute reached target; actual-offer propagation may lag
 * - Never rerun after any LIVE attempt; use Fresh audit only
 */
const MODULE_VERSION = "2026-08-29-amazon-b2b-six-resume-five-live-v1.0.0";
const ROUTE = "/amazon/price/b2b/six-resume-five-live";
const LIVE_CONFIRM = "AMAZON_B2B6_REMAINING5_LIVE_APPROVED_20260829_V1";
const REQUEST_TIMEOUT_MS = 20000;
const READ_RETRIES = 3;
const RETRY_BASE_MS = 700;
const VERIFY_ATTEMPTS = 8;
const VERIFY_WAIT_MS = 1800;
const originalListen = express.application.listen;

const FIRST = Object.freeze({ sku:"LeLib_SV1_16gb_256", asin:"B0G59QKJXB", normal:60000, effective:60000, points:600, min:40500, targetB2b:57000 });
const REMAINING = Object.freeze([
  Object.freeze({ sku:"RB-Y7G2-H0EK", asin:"B0GZGM1BND", normal:56000, effective:56000, points:560, min:40500, currentActualB2b:54363, targetB2b:53200 }),
  Object.freeze({ sku:"LeLib_SV1_16GB_SSD512", asin:"B0G5ZRLZZH", normal:68000, effective:68000, points:680, min:54900, currentActualB2b:65974, targetB2b:64600 }),
  Object.freeze({ sku:"ZK-N79H-VRJQ", asin:"B0D4QMJK1Z", normal:32000, effective:32000, points:320, min:30300, currentActualB2b:31046, targetB2b:30400 }),
  Object.freeze({ sku:"FU-OAHV-H4W4", asin:"B0H211KYDG", normal:65000, effective:65000, points:650, min:27900, currentActualB2b:63063, targetB2b:61700 }),
  Object.freeze({ sku:"LeLib_l580_i5-8G_16gb_SSD256", asin:"B0F333JB5Q", normal:44000, effective:44000, points:440, min:38500, currentActualB2b:42689, targetB2b:41800 }),
]);

function safeJsonParse(text){if(!text)return{};try{return JSON.parse(text);}catch{return{rawText:text};}}
function clone(v){return v===undefined?undefined:JSON.parse(JSON.stringify(v));}
function hasOwn(o,k){return Boolean(o)&&Object.prototype.hasOwnProperty.call(o,k);}
function numberOrNull(v){if(v===null||v===undefined||v==="")return null;if(typeof v==="object"&&v!==null){for(const k of ["amount","Amount","value","Value","pointsNumber","PointsNumber","points_number"]){if(v[k]!==undefined)return numberOrNull(v[k]);}}const n=Number(v);return Number.isFinite(n)?n:null;}
function epochOrNull(v){const t=Date.parse(String(v||""));return Number.isFinite(t)?t:null;}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function getSecret(){return String(process.env.AMAZON_STOCK_API_SECRET||"").trim();}
function getConfig(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();const marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||"A1VC38T7YXB528").trim();const endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("Missing env: SPAPI_SELLER_ID");return{sellerId,marketplaceId,endpoint};}

async function getLwaAccessToken(){const clientId=process.env.LWA_CLIENT_ID,clientSecret=process.env.LWA_CLIENT_SECRET,refreshToken=process.env.REFRESH_TOKEN;if(!clientId||!clientSecret||!refreshToken)throw new Error("Missing LWA env");const response=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken,client_id:clientId,client_secret:clientSecret})});const json=safeJsonParse(await response.text());if(!response.ok||!json.access_token)throw new Error(`LWA token error: ${response.status}`);return json.access_token;}

async function amazonRequest(url,options,allowRetry){const attempts=allowRetry?READ_RETRIES:1;let lastError=null;for(let attempt=1;attempt<=attempts;attempt+=1){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(url,{...options,signal:controller.signal});const json=safeJsonParse(await response.text());if(response.ok)return{response,json};const retryable=response.status===429||response.status>=500;if(!allowRetry||!retryable||attempt===attempts){const err=new Error(`SP-API error: ${response.status} ${JSON.stringify(json).slice(0,2500)}`);err.amazonBody=json;throw err;}await sleep(RETRY_BASE_MS*attempt);}catch(err){lastError=err;if(!allowRetry||attempt===attempts)throw err;await sleep(RETRY_BASE_MS*attempt);}finally{clearTimeout(timer);}}throw lastError||new Error("SP-API request failed");}
async function getListing(accessToken,sku){const{sellerId,marketplaceId,endpoint}=getConfig();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,offers,fulfillmentAvailability",issueLocale:"ja_JP"});const url=`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`;return(await amazonRequest(url,{method:"GET",headers:{"x-amz-access-token":accessToken,accept:"application/json"}},true)).json;}
async function patchListing(accessToken,sku,productType,offers,validationPreview){const{sellerId,marketplaceId,endpoint}=getConfig();const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP"});if(validationPreview)q.set("mode","VALIDATION_PREVIEW");const url=`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`;const body={productType,patches:[{op:"replace",path:"/attributes/purchasable_offer",value:offers}]};const json=(await amazonRequest(url,{method:"PATCH",headers:{"x-amz-access-token":accessToken,accept:"application/json","content-type":"application/json"},body:JSON.stringify(body)},validationPreview)).json;const issues=Array.isArray(json?.issues)?json.issues:[];const errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");return{json,issues,errors};}

function scheduleEntries(offer,key){const groups=Array.isArray(offer?.[key])?offer[key]:[];const out=[];groups.forEach((g,gi)=>(Array.isArray(g?.schedule)?g.schedule:[]).forEach((s,si)=>out.push({gi,si,s})));return out;}
function scheduleIsActive(s,now){const st=epochOrNull(s?.start_at),en=epochOrNull(s?.end_at);if(st!==null&&now<st)return false;if(en!==null&&now>=en)return false;return true;}
function activeSchedule(offer,key,now){return scheduleEntries(offer,key).filter(x=>scheduleIsActive(x.s,now)).sort((a,b)=>(epochOrNull(b.s?.start_at)??0)-(epochOrNull(a.s?.start_at)??0))[0]?.s||null;}
function audienceValue(offer){if(!offer)return"";if(typeof offer.audience==="string")return String(offer.audience).toUpperCase();return String(offer?.audience?.value||offer?.audience?.displayName||"").toUpperCase();}
function offerType(offer){return String(offer?.offerType||offer?.offer_type||"").toUpperCase();}
function offerPrice(offer){return offer&&hasOwn(offer,"price")?numberOrNull(offer.price):null;}
function parsePointsValue(raw){if(raw===null||raw===undefined||raw==="")return null;if(typeof raw!=="object")return numberOrNull(raw);for(const k of ["pointsNumber","PointsNumber","points_number","amount","Amount","value","Value"]){if(raw[k]!==undefined){const n=numberOrNull(raw[k]);if(n!==null)return n;}}return null;}
function actualOffers(listing){const{marketplaceId}=getConfig();const offers=Array.isArray(listing?.offers)?listing.offers:[];const market=offers.filter(o=>{const id=String(o?.marketplaceId||o?.marketplace_id||"");return!id||id===marketplaceId;});const b2c=market.find(o=>offerType(o)==="B2C"||audienceValue(o)==="ALL")||null;const b2b=market.find(o=>offerType(o)==="B2B"||audienceValue(o)==="B2B")||null;return{b2cPresent:Boolean(b2c),b2cPrice:offerPrice(b2c),pointsPresent:Boolean(b2c&&hasOwn(b2c,"points")),points:b2c&&hasOwn(b2c,"points")?parsePointsValue(b2c.points):null,b2bPresent:Boolean(b2b),b2bPrice:offerPrice(b2b)};}
function quantityPlanPresent(offer){return scheduleEntries(offer,"quantity_discount_plan").length>0;}

function analyze(spec,listing,now=Date.now()){const summary=Array.isArray(listing?.summaries)?listing.summaries[0]||{}:{};const attrs=listing?.attributes||{},issues=Array.isArray(listing?.issues)?listing.issues:[];const errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR"),statuses=Array.isArray(summary?.status)?summary.status.map(String):[];const offers=Array.isArray(attrs?.purchasable_offer)?clone(attrs.purchasable_offer):[];const indexed=offers.map((offer,index)=>({offer,index}));const consumers=indexed.filter(x=>audienceValue(x.offer)==="ALL");const b2bs=indexed.filter(x=>audienceValue(x.offer)==="B2B");const consumer=consumers.length===1?consumers[0].offer:null;const b2b=b2bs.length===1?b2bs[0].offer:null;const normal=numberOrNull(activeSchedule(consumer,"our_price",now)?.value_with_tax),sale=numberOrNull(activeSchedule(consumer,"discounted_price",now)?.value_with_tax),effective=sale!==null?sale:normal,min=numberOrNull(activeSchedule(consumer,"minimum_seller_allowed_price",now)?.value_with_tax),max=numberOrNull(activeSchedule(consumer,"maximum_seller_allowed_price",now)?.value_with_tax),b2bAttributePrice=numberOrNull(activeSchedule(b2b,"our_price",now)?.value_with_tax);const qty=numberOrNull(listing?.fulfillmentAvailability?.[0]?.quantity)??numberOrNull(attrs?.fulfillment_availability?.[0]?.quantity)??0;return{spec,asin:String(summary?.asin||""),productType:String(summary?.productType||""),statuses,buyable:statuses.includes("BUYABLE"),errors,qty,offers,consumer,consumerCount:consumers.length,b2b,b2bIndex:b2bs.length===1?b2bs[0].index:-1,b2bCount:b2bs.length,normal,sale,effective,min,max,b2bAttributePrice,actual:actualOffers(listing),quantityPlanPresent:b2b?quantityPlanPresent(b2b):false};}

function baseBlocks(state){const s=state.spec,b=[];if(state.asin!==s.asin)b.push(`ASIN_MISMATCH:${state.asin}`);if(!state.productType)b.push("PRODUCT_TYPE_MISSING");if(!state.buyable)b.push(`NOT_BUYABLE:${state.statuses.join(",")}`);if(state.errors.length)b.push(`LISTING_ERRORS:${state.errors.map(x=>String(x?.code||"")).join(",")}`);if(!(state.qty>0))b.push(`NO_INVENTORY:${state.qty}`);if(state.consumerCount!==1)b.push(`CONSUMER_OFFER_COUNT:${state.consumerCount}`);if(!state.actual.b2cPresent||state.actual.b2cPrice===null)b.push("ACTUAL_B2C_OFFER_MISSING");if(!state.actual.pointsPresent||state.actual.points===null)b.push("AMAZON_POINTS_MISSING");if(state.normal!==s.normal)b.push(`NORMAL_PRICE_DRIFT:${state.normal}`);if(state.effective!==s.effective)b.push(`EFFECTIVE_PRICE_DRIFT:${state.effective}`);if(state.actual.b2cPrice!==s.normal)b.push(`ACTUAL_B2C_DRIFT:${state.actual.b2cPrice}`);if(state.actual.points!==s.points)b.push(`POINTS_DRIFT:${state.actual.points}`);if(state.min!==s.min)b.push(`MINIMUM_DRIFT:${state.min}`);if(s.targetB2b<s.min)b.push(`TARGET_BELOW_MIN:${s.targetB2b}<${s.min}`);if(state.effective===null||s.targetB2b>=state.effective)b.push(`TARGET_NOT_BELOW_EFFECTIVE:${s.targetB2b}>=${state.effective}`);if(state.max!==null&&s.targetB2b>state.max)b.push(`TARGET_ABOVE_MAX:${s.targetB2b}>${state.max}`);return b;}
function firstGuardBlocks(state){const b=baseBlocks(state);if(state.b2bCount!==1)b.push(`FIRST_B2B_ATTRIBUTE_COUNT:${state.b2bCount}`);if(state.b2bAttributePrice!==FIRST.targetB2b)b.push(`FIRST_B2B_ATTRIBUTE_PRICE:${state.b2bAttributePrice}`);if(state.quantityPlanPresent)b.push("FIRST_QUANTITY_PLAN_PRESENT");if(!state.actual.b2bPresent||state.actual.b2bPrice!==FIRST.targetB2b)b.push(`FIRST_ACTUAL_B2B:${state.actual.b2bPrice}`);return b;}
function remainingPreflightBlocks(state){const s=state.spec,b=baseBlocks(state);if(state.b2bCount!==0)b.push(`EXPLICIT_B2B_ATTRIBUTE_ALREADY_PRESENT:${state.b2bCount}:${state.b2bAttributePrice}`);if(state.quantityPlanPresent)b.push("EXISTING_QUANTITY_PLAN_PRESENT");if(!state.actual.b2bPresent||state.actual.b2bPrice===null)b.push("ACTUAL_B2B_OFFER_MISSING");if(state.actual.b2bPrice!==s.currentActualB2b)b.push(`ACTUAL_B2B_DRIFT:${state.actual.b2bPrice}`);return b;}

function priceTemplateFrom(offer){return Array.isArray(offer?.our_price)&&offer.our_price.length?clone(offer.our_price[0]||{}):null;}
function buildAppendOffers(state){if(state.b2bCount!==0)throw new Error("explicit B2B attribute already present");const offers=clone(state.offers);const b2b=clone(state.consumer);b2b.audience="B2B";delete b2b.discounted_price;delete b2b.minimum_seller_allowed_price;delete b2b.maximum_seller_allowed_price;delete b2b.quantity_discount_plan;const template=priceTemplateFrom(b2b)||priceTemplateFrom(state.consumer);if(!template)throw new Error("our_price template missing");template.schedule=[{value_with_tax:state.spec.targetB2b}];b2b.our_price=[template];if(quantityPlanPresent(b2b))throw new Error("quantity plan unexpectedly present");offers.push(b2b);return offers;}

function attributeVerifyBlocks(state){const s=state.spec,b=baseBlocks(state);if(state.b2bCount!==1)b.push(`POST_B2B_ATTRIBUTE_COUNT:${state.b2bCount}`);if(state.b2bAttributePrice!==s.targetB2b)b.push(`POST_B2B_ATTRIBUTE_PRICE:${state.b2bAttributePrice}`);if(state.quantityPlanPresent)b.push("POST_QUANTITY_PLAN_PRESENT");if(!state.actual.b2bPresent||![s.currentActualB2b,s.targetB2b].includes(state.actual.b2bPrice))b.push(`POST_ACTUAL_B2B_UNEXPECTED:${state.actual.b2bPrice}`);return b;}
async function verifyAttributeApplied(accessToken,spec){let state=null,blocks=[];for(let attempt=1;attempt<=VERIFY_ATTEMPTS;attempt+=1){state=analyze(spec,await getListing(accessToken,spec.sku),Date.now());blocks=attributeVerifyBlocks(state);if(!blocks.length)return{verified:true,attempt,state,blocks:[]};if(attempt<VERIFY_ATTEMPTS)await sleep(VERIFY_WAIT_MS);}return{verified:false,attempt:VERIFY_ATTEMPTS,state,blocks};}
function stateSummary(state){return state?{sku:state.spec.sku,asin:state.asin,normalPrice:state.normal,effectivePrice:state.effective,amazonPoints:state.actual.points,minimumSellerAllowed:state.min,b2bAttributePrice:state.b2bAttributePrice,actualOfferB2BPrice:state.actual.b2bPrice,quantityPlanPresent:state.quantityPlanPresent,buyable:state.buyable,errorCount:state.errors.length,availableQuantity:state.qty}:null;}

async function readRemaining(accessToken){const out=[];for(const spec of REMAINING)out.push(analyze(spec,await getListing(accessToken,spec.sku),Date.now()));return out;}
async function readFirst(accessToken){return analyze(FIRST,await getListing(accessToken,FIRST.sku),Date.now());}

async function handler(req,res){let validationPreviewCalls=0,liveCalls=0;const completed=[];let activeLiveSku=null;try{const secret=getSecret();if(!secret)return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"CONFIG_ERROR",validationPreviewCalls:0,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,error:"AMAZON_STOCK_API_SECRET is not set"});if(String(req.headers["x-api-secret"]||"")!==secret)return res.status(401).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"UNAUTHORIZED",validationPreviewCalls:0,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,error:"Unauthorized"});if(String(req.body?.confirm||"")!==LIVE_CONFIRM)return res.status(400).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"LIVE_CONFIRM_MISMATCH",validationPreviewCalls:0,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,error:`confirm must equal ${LIVE_CONFIRM}`});

const accessToken=await getLwaAccessToken();
const first1=await readFirst(accessToken);const firstBlocks1=firstGuardBlocks(first1);const rem1=await readRemaining(accessToken);const remFailures1=rem1.map(s=>({sku:s.spec.sku,blocks:remainingPreflightBlocks(s),state:stateSummary(s)})).filter(x=>x.blocks.length);if(firstBlocks1.length||remFailures1.length)return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_PREFLIGHT_BLOCKED_NO_LIVE",validationPreviewCalls:0,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,firstGuardBlocks:firstBlocks1,remainingFailures:remFailures1,firstState:stateSummary(first1)});

for(const state of rem1){const offers=buildAppendOffers(state);const preview=await patchListing(accessToken,state.spec.sku,state.productType,offers,true);validationPreviewCalls+=1;if(preview.errors.length)return res.status(422).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_VALIDATION_PREVIEW_FAILED_NO_LIVE",validationPreviewCalls,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,sku:state.spec.sku,issues:preview.issues});}

const first2=await readFirst(accessToken);const firstBlocks2=firstGuardBlocks(first2);const rem2=await readRemaining(accessToken);const remFailures2=rem2.map(s=>({sku:s.spec.sku,blocks:remainingPreflightBlocks(s),state:stateSummary(s)})).filter(x=>x.blocks.length);if(firstBlocks2.length||remFailures2.length)return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_SECOND_PREFLIGHT_BLOCKED_NO_LIVE",validationPreviewCalls,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,firstGuardBlocks:firstBlocks2,remainingFailures:remFailures2,firstState:stateSummary(first2)});

for(const spec of REMAINING){const fresh=analyze(spec,await getListing(accessToken,spec.sku),Date.now());const blocks=remainingPreflightBlocks(fresh);if(blocks.length){const changed=liveCalls>0;return res.status(changed?202:409).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:changed?"RESUME5_PARTIAL_LIVE_APPLIED_DO_NOT_RERUN":"RESUME5_FINAL_PREFLIGHT_BLOCKED_NO_LIVE",validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,completed,blockedSku:spec.sku,blocks,state:stateSummary(fresh),nextStep:changed?"FRESH_AUDIT_ONLY_DO_NOT_RERUN_RESUME5":undefined});}
const offers=buildAppendOffers(fresh);activeLiveSku=spec.sku;liveCalls+=1;const accepted=await patchListing(accessToken,spec.sku,fresh.productType,offers,false);if(accepted.errors.length)return res.status(202).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_LIVE_SUBMITTED_WITH_ERROR_ISSUES_DO_NOT_RERUN",validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,completed,activeLiveSku,issues:accepted.issues,nextStep:"FRESH_AUDIT_ONLY_DO_NOT_RERUN_RESUME5"});const verification=await verifyAttributeApplied(accessToken,spec);if(!verification.verified)return res.status(202).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_LIVE_SUBMITTED_ATTRIBUTE_VERIFY_INCOMPLETE_DO_NOT_RERUN",validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,completed,activeLiveSku,verifyAttempts:verification.attempt,verifyBlocks:verification.blocks,state:stateSummary(verification.state),nextStep:"FRESH_AUDIT_ONLY_DO_NOT_RERUN_RESUME5"});completed.push({sku:spec.sku,asin:spec.asin,fromB2b:spec.currentActualB2b,targetB2b:spec.targetB2b,verifyAttempts:verification.attempt,actualPropagation:verification.state.actual.b2bPrice===spec.targetB2b?"PROPAGATED":"PENDING",state:stateSummary(verification.state)});activeLiveSku=null;}

const pending=completed.filter(x=>x.actualPropagation!=="PROPAGATED").length;return res.status(200).json({ok:true,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_LIVE_ALL_5_ATTRIBUTE_VERIFIED",validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,completed,actualPropagationPendingCount:pending,nextStep:"RUN_B2B6_FINAL_FRESH_AUDIT_DO_NOT_RERUN_RESUME5"});
}catch(err){if(liveCalls>0)return res.status(202).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_LIVE_ATTEMPTED_RESULT_AMBIGUOUS_DO_NOT_RERUN",validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,completed,activeLiveSku,error:err?.message||String(err),nextStep:"FRESH_AUDIT_ONLY_DO_NOT_RERUN_RESUME5"});return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"RESUME5_ERROR_BEFORE_LIVE_NO_MUTATION",validationPreviewCalls,liveCalls:0,persistentAmazonWrites:0,externalChanges:0,error:err?.message||String(err)});}}

express.application.listen=function amazonB2BSixResumeFiveLiveListen(...args){const exists=Boolean(this?._router?.stack?.some(layer=>layer?.route?.path===ROUTE));if(!exists)this.post(ROUTE,handler);return originalListen.apply(this,args);};
