import express from "express";
import fetch from "node-fetch";
import "dotenv/config";

const MODULE_VERSION = "2026-08-26-g83-41170-price-test-live-v1.0.0";
const ROUTE = "/amazon/price/g83/41170-test/live";
const SKU = "E7-YLJ3-F9CY";
const ASIN = "B0GZBHBQN2";
const NORMAL = 58000;
const CURRENT_SALE = 42000;
const TARGET_SALE = 41170;
const MIN_ALLOWED = 36100;
const SAFE_FLOOR = 36400;
const B2B = 39900;
const DURATION_HOURS = 48;
const CONFIRM = "G83-41170-LIVE-APPROVED-20260826";
const VERIFY_ATTEMPTS = 10;
const VERIFY_WAIT_MS = 3000;
const originalPost = express.application.post;
const originalUse = express.application.use;

const parse = t => { try { return t ? JSON.parse(t) : {}; } catch { return { rawText:t }; } };
const num = v => (v===null||v===undefined||v==="") ? null : (Number.isFinite(Number(v)) ? Number(v) : null);
const epoch = v => { const t=Date.parse(String(v||"")); return Number.isFinite(t)?t:null; };
const secret = () => String(process.env.AMAZON_STOCK_API_SECRET||"").trim();
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();const marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||"A1VC38T7YXB528").trim();const endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("Missing env: SPAPI_SELLER_ID");return{sellerId,marketplaceId,endpoint};}
async function lwa(){const clientId=process.env.LWA_CLIENT_ID,clientSecret=process.env.LWA_CLIENT_SECRET,refreshToken=process.env.REFRESH_TOKEN;if(!clientId||!clientSecret||!refreshToken)throw new Error("Missing LWA env");const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken,client_id:clientId,client_secret:clientSecret})});const j=parse(await r.text());if(!r.ok||!j.access_token)throw new Error(`LWA token error: ${r.status}`);return j.access_token;}
async function amazon({method,url,token,body}){const r=await fetch(url,{method,headers:{"x-amz-access-token":token,accept:"application/json",...(body?{"content-type":"application/json"}:{})},...(body?{body:JSON.stringify(body)}:{})});const j=parse(await r.text());if(!r.ok)throw new Error(`SP-API ${method} error: ${r.status} ${JSON.stringify(j)}`);return j;}
async function getListing(token){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,fulfillmentAvailability",issueLocale:"ja_JP"});return amazon({method:"GET",url:`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(SKU)}?${q}`,token});}
function schedules(o,k){const s=o?.[k]?.[0]?.schedule;return Array.isArray(s)?s:[];}
function active(o,k,now){return schedules(o,k).filter(s=>{const st=epoch(s?.start_at),en=epoch(s?.end_at);return(st===null||now>=st)&&(en===null||now<en);}).sort((a,b)=>(epoch(b?.start_at)??0)-(epoch(a?.start_at)??0))[0]||null;}
function qp(o){return o?.quantity_discount_plan??o?.quantity_discount_plans??null;}
function qpOk(plan){const t=JSON.stringify(plan).toLowerCase();return t.includes("percent")&&/"lower_?bound"\s*:\s*10(?:\.0+)?/.test(t)&&/"value"\s*:\s*3(?:\.0+)?/.test(t);}
function analyze(raw,now=Date.now()){const summary=Array.isArray(raw?.summaries)?raw.summaries[0]||{}:{};const attrs=raw?.attributes||{};const issues=Array.isArray(raw?.issues)?raw.issues:[];const av=Array.isArray(raw?.fulfillmentAvailability)?raw.fulfillmentAvailability[0]||{}:{};const offers=Array.isArray(attrs?.purchasable_offer)?attrs.purchasable_offer:[];const ci=offers.findIndex(o=>String(o?.audience||"ALL").toUpperCase()==="ALL");const bi=offers.findIndex(o=>String(o?.audience||"").toUpperCase()==="B2B");const c=ci>=0?offers[ci]:null,b=bi>=0?offers[bi]:null;const sale=active(c,"discounted_price",now);return{asin:String(summary?.asin||""),productType:String(summary?.productType||""),statuses:Array.isArray(summary?.status)?summary.status.map(String):[],errorCount:issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR").length,availableQuantity:num(av?.quantity)??num(attrs?.fulfillment_availability?.[0]?.quantity)??0,offers,ci,bi,c,b,normal:num(active(c,"our_price",now)?.value_with_tax),sale:num(sale?.value_with_tax),saleStart:sale?.start_at||null,saleEnd:sale?.end_at||null,min:num(active(c,"minimum_seller_allowed_price",now)?.value_with_tax),b2b:num(active(b,"our_price",now)?.value_with_tax),plan:qp(b),planOk:qpOk(qp(b))};}
function protectedSnapshot(s){const c=JSON.parse(JSON.stringify(s.c||{}));delete c.discounted_price;return{consumerWithoutDiscount:c,nonConsumer:s.offers.filter((_,i)=>i!==s.ci)};}
function canon(v){if(Array.isArray(v))return v.map(canon);if(v&&typeof v==="object")return Object.keys(v).sort().reduce((o,k)=>(o[k]=canon(v[k]),o),{});return v;}
const same=(a,b)=>JSON.stringify(canon(a))===JSON.stringify(canon(b));
function assertState(s){const e=[];if(s.asin!==ASIN)e.push(`asin=${s.asin}`);if(!s.productType)e.push("productType missing");if(!s.statuses.includes("BUYABLE"))e.push("BUYABLE missing");if(s.errorCount!==0)e.push(`errors=${s.errorCount}`);if(!(s.availableQuantity>0))e.push(`qty=${s.availableQuantity}`);if(s.normal!==NORMAL)e.push(`normal=${s.normal}`);if(s.sale!==CURRENT_SALE)e.push(`sale=${s.sale}`);if(s.min!==MIN_ALLOWED)e.push(`min=${s.min}`);if(s.b2b!==B2B)e.push(`b2b=${s.b2b}`);if(!s.planOk)e.push("qtyPlan mismatch");if(TARGET_SALE<SAFE_FLOOR)e.push("below safe floor");if(TARGET_SALE<=B2B)e.push("consumer target <= B2B");if(e.length){const er=new Error(`G83 41170 LIVE preflight failed: ${e.join(" / ")}`);er.code="PREFLIGHT_FAILED";throw er;}}
function build(s,now){const offers=JSON.parse(JSON.stringify(s.offers));const c=offers[s.ci];const container=c?.discounted_price?.[0];if(!container||!Array.isArray(container.schedule)||!container.schedule.length)throw new Error("discounted_price schema missing");const t=JSON.parse(JSON.stringify(active(c,"discounted_price",now)||container.schedule[0]));const startAt=new Date(now-60000).toISOString();const endAt=new Date(now+DURATION_HOURS*3600000).toISOString();t.value_with_tax=TARGET_SALE;t.start_at=startAt;t.end_at=endAt;container.schedule=[t];return{startAt,endAt,body:{productType:s.productType,patches:[{op:"replace",path:"/attributes/purchasable_offer",value:offers}]}};}
async function patchLive(token,body){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP"});const j=await amazon({method:"PATCH",url:`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(SKU)}?${q}`,token,body});const errs=(Array.isArray(j?.issues)?j.issues:[]).filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");if(errs.length)throw new Error(`Amazon LIVE ERROR issues: ${JSON.stringify(errs)}`);return j;}
async function verify(token,beforeProtected){let last=null;for(let i=1;i<=VERIFY_ATTEMPTS;i++){last=analyze(await getListing(token));const p=protectedSnapshot(last);const core=last.asin===ASIN&&last.statuses.includes("BUYABLE")&&last.errorCount===0&&last.normal===NORMAL&&last.sale===TARGET_SALE&&last.min===MIN_ALLOWED&&last.b2b===B2B&&last.planOk;const protectedPass=same(beforeProtected.consumerWithoutDiscount,p.consumerWithoutDiscount)&&same(beforeProtected.nonConsumer,p.nonConsumer);if(core&&protectedPass)return{verified:true,attempt:i,state:last};if(i<VERIFY_ATTEMPTS)await new Promise(r=>setTimeout(r,VERIFY_WAIT_MS));}return{verified:false,state:last};}
async function handler(req,res){try{const sec=secret();if(!sec)return res.status(500).json({ok:false,externalChanges:0,error:"secret missing"});if(String(req.headers["x-api-secret"]||"")!==sec)return res.status(401).json({ok:false,externalChanges:0,error:"Unauthorized"});if(req.body?.confirm!==CONFIRM)return res.status(400).json({ok:false,externalChanges:0,error:`confirm must equal ${CONFIRM}`});if(Number(req.body?.targetSalePrice)!==TARGET_SALE||Number(req.body?.durationHours)!==DURATION_HOURS)return res.status(400).json({ok:false,externalChanges:0,error:"scope mismatch"});const token=await lwa();const before=analyze(await getListing(token));assertState(before);const protectedBefore=protectedSnapshot(before);const built=build(before,Date.now());const accepted=await patchLive(token,built.body);const verification=await verify(token,protectedBefore);if(!verification.verified)return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,status:"VERIFICATION_FAILED",externalChanges:0,accepted,target:{salePrice:TARGET_SALE,startAt:built.startAt,endAt:built.endAt},after:verification.state});return res.json({ok:true,moduleVersion:MODULE_VERSION,status:"COMPLETED",externalChanges:1,accepted,target:{salePrice:TARGET_SALE,startAt:built.startAt,endAt:built.endAt},verification:{attempt:verification.attempt,normalPrice:verification.state.normal,activeSalePrice:verification.state.sale,minimumSellerAllowedPrice:verification.state.min,b2bPrice:verification.state.b2b,quantityDiscountPlan:verification.state.plan,availableQuantity:verification.state.availableQuantity,statuses:verification.state.statuses,listingErrorCount:verification.state.errorCount}});}catch(err){return res.status(err?.code==="PREFLIGHT_FAILED"?409:500).json({ok:false,moduleVersion:MODULE_VERSION,status:err?.code||"ERROR",externalChanges:0,error:err?.message||String(err)});}}
express.application.post=function patchedPost(path,...handlers){if(path===ROUTE)return originalPost.call(this,path,...handlers);return originalPost.call(this,path,...handlers);};
express.application.use=function patchedUse(...args){const result=originalUse.apply(this,args);if(!this.__g8341170LiveInstalled){this.__g8341170LiveInstalled=true;originalPost.call(this,ROUTE,handler);console.log(`${MODULE_VERSION} route installed: POST ${ROUTE}`);}return result;};
