import express from "express";
import fetch from "node-fetch";
import crypto from "crypto";
import "dotenv/config";

const MODULE_VERSION = "2026-08-30-latitude5330-shared-main-image-v1.0.0";
const ROUTE = "/amazon/listing/latitude5330-shared-main-image";
const MARKETPLACE_ID = "A1VC38T7YXB528";
const REQUEST_TIMEOUT_MS = 12000;
const VERIFY_ATTEMPTS = 3;
const VERIFY_GAP_MS = 1500;
const originalListen = express.application.listen;

const G = Object.freeze({
  productType: "NOTEBOOK_COMPUTER",
  parentSku: "latitude5330-i5-12g-16gb-storage-parent",
  imageUrl: "https://amazon-webhook-api.onrender.com/assets/y3-main.jpg",
  imageSha256: "555b77d6e1b1fcffe310f679de231885273053a5cc10f137221994553b52be06",
  confirmLive: "CONFIRM_LAT5330_SHARED_MAIN_IMAGE_20260830",
  children: [
    { sku: "Y3-30YC-UORU", asin: "B0HGDZNVQN", storageGB: 256 },
    { sku: "latitude5330-i5-12g-16gb-ssd512", asin: "B0HH3ST712", storageGB: 512 },
  ],
});

function jparse(t){try{return t?JSON.parse(t):{};}catch{return {rawText:t};}}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
function secret(){return String(process.env.AMAZON_STOCK_API_SECRET||"").trim();}
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();const marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||MARKETPLACE_ID).trim();const endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("Missing env: SPAPI_SELLER_ID");if(marketplaceId!==MARKETPLACE_ID)throw new Error(`GUARD_BLOCKED marketplace=${marketplaceId}`);return {sellerId,marketplaceId,endpoint};}
async function ft(url,opt={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...opt,signal:c.signal});}finally{clearTimeout(t);}}
async function token(){const clientId=process.env.LWA_CLIENT_ID,clientSecret=process.env.LWA_CLIENT_SECRET,refreshToken=process.env.REFRESH_TOKEN;if(!clientId||!clientSecret||!refreshToken)throw new Error("Missing LWA env");const r=await ft("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:refreshToken,client_id:clientId,client_secret:clientSecret})});const x=jparse(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA token error ${r.status}`);return x.access_token;}
async function req(url,a,opt={}){const r=await ft(url,{method:opt.method||"GET",headers:{"x-amz-access-token":a,accept:"application/json",...(opt.body?{"content-type":"application/json"}:{})},...(opt.body?{body:JSON.stringify(opt.body)}:{})});return {httpStatus:r.status,responseOk:r.ok,body:jparse(await r.text())};}
async function inspectAsset(){const r=await ft(G.imageUrl,{headers:{accept:"image/jpeg"}});const b=Buffer.from(await r.arrayBuffer());const ct=String(r.headers.get("content-type")||"").toLowerCase();const sha=crypto.createHash("sha256").update(b).digest("hex");if(!r.ok)throw new Error(`ASSET_NOT_READY HTTP=${r.status}`);if(!ct.includes("image/jpeg"))throw new Error(`ASSET_NOT_READY contentType=${ct}`);if(sha!==G.imageSha256)throw new Error(`ASSET_NOT_READY sha256=${sha}`);return {httpStatus:r.status,contentType:ct,byteLength:b.length,sha256:sha,url:G.imageUrl};}
async function getListing(a,sku){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,offers,fulfillmentAvailability",issueLocale:"ja_JP"});const x=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a);if(!x.responseOk)throw new Error(`GET ${sku} HTTP=${x.httpStatus}`);return x.body;}
function sv(x){return Array.isArray(x?.summaries)?x.summaries[0]||{}:{};} function at(x){return x?.attributes&&typeof x.attributes==="object"?x.attributes:{};}
function nested(a,k,outer){return a?.[k]?.[0]?.[outer]?.[0]?.value;} function numEq(a,b){return Number.isFinite(Number(a))&&Math.abs(Number(a)-Number(b))<0.0001;}
function assertChild(x,g){const s=sv(x),a=at(x);if(String(s.asin||"")!==g.asin)throw new Error(`SOURCE_DRIFT asin ${g.sku}`);if(String(s.productType||"")!==G.productType)throw new Error(`SOURCE_DRIFT productType ${g.sku}`);if(String(a?.parentage_level?.[0]?.value||"").toLowerCase()!=="child")throw new Error(`SOURCE_DRIFT parentage ${g.sku}`);if(String(a?.child_parent_sku_relationship?.[0]?.parent_sku||"")!==G.parentSku)throw new Error(`SOURCE_DRIFT parent ${g.sku}`);const storage=numEq(nested(a,"hard_disk","size"),g.storageGB)||numEq(nested(a,"flash_memory","installed_size"),g.storageGB);if(!storage)throw new Error(`SOURCE_DRIFT storage ${g.sku}`);if(!numEq(nested(a,"ram_memory","installed_size"),16))throw new Error(`SOURCE_DRIFT RAM ${g.sku}`);return {sku:g.sku,asin:g.asin,storageGB:g.storageGB,currentImage:Array.isArray(a.main_product_image_locator)?a.main_product_image_locator:[],issueCodes:(Array.isArray(x.issues)?x.issues:[]).map(i=>String(i?.code||"")).filter(Boolean)};}
function patchFor(x){const a=at(x);return {op:Array.isArray(a.main_product_image_locator)&&a.main_product_image_locator.length?"replace":"add",path:"/attributes/main_product_image_locator",value:[{media_location:G.imageUrl,marketplace_id:MARKETPLACE_ID}]};}
async function patch(a,sku,p,preview){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",includedData:"issues"});if(preview)q.set("mode","VALIDATION_PREVIEW");return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a,{method:"PATCH",body:{productType:G.productType,patches:[p]}});}
function ps(r){const issues=Array.isArray(r?.body?.issues)?r.body.issues:[];const errors=issues.filter(i=>String(i?.severity||"").toUpperCase()==="ERROR");const status=String(r?.body?.status||"").toUpperCase();return {httpStatus:r.httpStatus,responseOk:r.responseOk,status,submissionId:String(r?.body?.submissionId||""),issueCount:issues.length,errorCount:errors.length,issues,valid:r.responseOk&&errors.length===0&&["VALID","ACCEPTED"].includes(status)};}
function imageMatches(x){const rows=at(x).main_product_image_locator||[];return rows.some(r=>String(r?.media_location||"")===G.imageUrl);}
async function handler(req0,res){let writes=0;try{const sec=secret();if(!sec)return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,externalChanges:0,error:"secret missing"});if(String(req0.headers["x-api-secret"]||"")!==sec)return res.status(401).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,externalChanges:0,error:"Unauthorized"});const mode=String(req0.body?.mode||"PREVIEW").toUpperCase();if(!["PREVIEW","LIVE"].includes(mode))throw new Error("mode must be PREVIEW or LIVE");if(mode==="LIVE"&&String(req0.body?.confirmLive||"")!==G.confirmLive)throw new Error("LIVE_GUARD_BLOCKED confirm token mismatch");const asset=await inspectAsset();const a=await token();const liveListings=[];for(const g of G.children){const x=await getListing(a,g.sku);liveListings.push({g,x,snapshot:assertChild(x,g),patch:patchFor(x)});}const previews=[];for(const row of liveListings){previews.push({sku:row.g.sku,...ps(await patch(a,row.g.sku,row.patch,true))});}if(!previews.every(x=>x.valid))return res.status(200).json({ok:true,moduleVersion:MODULE_VERSION,route:ROUTE,mode,status:"BLOCK",externalChanges:0,asset,previews,children:liveListings.map(x=>x.snapshot),next:"STOP. No live image write."});if(mode==="PREVIEW")return res.status(200).json({ok:true,moduleVersion:MODULE_VERSION,route:ROUTE,mode,status:"PASS",readOnly:true,externalChanges:0,asset,previews,children:liveListings.map(x=>x.snapshot),readyForLive:true,next:`Run LIVE once with confirmLive=${G.confirmLive}`});const live=[];for(const row of liveListings){const r=ps(await patch(a,row.g.sku,row.patch,false));live.push({sku:row.g.sku,...r});if(!r.valid)return res.status(502).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,mode,status:"LIVE_PARTIAL_STOP",externalChanges:writes,asset,previews,live,next:"STOP. Do not retry automatically."});writes++;}const verification=[];for(const g of G.children){let ok=false;let snap={};for(let i=1;i<=VERIFY_ATTEMPTS;i++){if(i>1)await sleep(VERIFY_GAP_MS);const x=await getListing(a,g.sku);ok=imageMatches(x);snap={attempt:i,imageMatches:ok,issueCodes:(Array.isArray(x.issues)?x.issues:[]).map(z=>String(z?.code||"")).filter(Boolean)};if(ok)break;}verification.push({sku:g.sku,...snap});}const postVerified=verification.every(v=>v.imageMatches);return res.status(200).json({ok:true,moduleVersion:MODULE_VERSION,route:ROUTE,mode,status:postVerified?"PASS":"PENDING_PROPAGATION",externalChanges:writes,asset,previews,live,verification,postVerified,next:postVerified?"Shared main image locator persisted on both children. Amazon image processing may still take time.":"LIVE accepted. Do not retry; use Seller Central if Amazon image processing stalls."});}catch(err){return res.status(400).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,externalChanges:writes,error:err?.message||String(err),next:String(err?.message||"").startsWith("ASSET_NOT_READY")?"STOP_API_AND_USE_SELLER_CENTRAL":"STOP. Do not retry automatically."});}}

express.application.listen=function latitude5330SharedMainImageListen(...args){const exists=Boolean(this?._router?.stack?.some(layer=>layer?.route?.path===ROUTE));if(!exists)this.post(ROUTE,handler);return originalListen.apply(this,args);};
